config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'site#index'

  authenticate :user do
    resources :draws
  end
end

app/models/draw.rb
class Draw < ActiveRecord::Base
  has_many :draws
  has_many :matches
  has_one :game

  accepts_nested_attributes_for :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :draw
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :draw
end

app/models/number.rb
class Number < ActiveRecord::Base
  belongs_to :draw
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/draws_controller.rb
class DrawsController < ApplicationController
  include HTTParty

  def index
    @draws = getDrawsFromAPI
    # TODO: ...
  end

  private
  def getDrawsFromAPI
    rawdata = HTTParty.get('http://130.206.85.53:3000/draws')
    return rawdata["objects"]
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draws_helper.rb
module DrawsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SbChallenge</title>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "SocialBets", root_path, class: "brand-logo" %>
        <a href="#" data-activates="mobile-menu" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Botes", draws_path, method: :get %></li>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
        </ul>
        <ul class="side-nav" id="mobile-menu">
          <li><%= link_to "Botes", draws_path, method: :get %></li>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </nav>
  </header>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>

  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
      © 2015 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/site/index.erb
<h1>Hello!</h1>